### ISSUE TITLE
Feature: Add support for snippets

### ISSUE THREAD

**Issue by daattali** [dominodatalab/low-code-assistant-rstudio#20]

**Comment by jddavis1000** [comment]
Provide custom snippets in Python and R so that data scientists can efficiently run distributed computing paradigms in local or cluster mode.

**Comment by daattali** [comment]
A snippets library is a folder named "snippets", and the snippets inside it are any files that have an extension of ".R"

When opening the snippets wizard, a few snippets libraries are "merged" together:
- a default built-in snippets library that ships with LCA-R
- any git repositories (check envvar["DOMINO_IMPORTED_CODE_DIR"] for the root of imported git repositories, then check each repo if it has a snippets library)
- any imported projects (look for all envvars with regex DOMINO_.*_WORKING_DIR)
- current project snippets library (envvar["DOMINO_WORKING_DIR"])

**Comment by daattali** [comment]
To check if a folder is git-writable (need to do more testing on this, may not always work)

```r
is_git_writable <- function(dir) {
  tryCatch({
    processx::run(
      "git",
      c("push", "--dry-run", "--force", "--no-verify"),
      error_on_status = FALSE,
      env = c("current", "GIT_ASKPASS" = "", "SSH_ASKPASS" = ""),
      wd = dir
    )$status == 0
  }, error = function(err) FALSE)
}
```

**Comment by daattali** [comment]
More reliable way to check for git writability:

```r
tryCatch({
  setwd(dir)
  gitcreds::gitcreds_get(use_cache = FALSE, set_cache = FALSE)
  processx::run("git", c("push", "--dry-run", "--force", "--no-verify"))
  TRUE
}, error = function(err) FALSE)
```
