### ISSUE TITLE
Viz module: dont load `ggplot2` for every code chunk

### ISSUE THREAD

**Issue by daattali** [dominodatalab/low-code-assistant-rstudio#21]

**Comment by datawookie** [comment]
Hehe. Was just about to log this issue! :)

**Comment by daattali** [comment]
There was a suggestion made on slack to see if the package is already attached or not, but I don't like that solution because the package could be attached in the globalenv, but it may not be in the current script.

I think I would opt for a more general implementation, by preventing the insertion of any `libraray(...)` call into a script that already contains that library.
