### ISSUE TITLE
Add option to select delimeter

### ISSUE THREAD

**Issue by datawookie** [dominodatalab/low-code-assistant-rstudio#42]
Should have option to choose alternative delimeters.

![image](https://user-images.githubusercontent.com/6134409/206123222-3738e780-8f24-42d0-8d96-be94dee1d67b.png)

**Comment by daattali** [comment]
I'm curious if the python LCA allows you to choose delimeter?

**Comment by daattali** [comment]
I added a few different options depending on the file type. The UI for it isn't great, but because this doesn't exist in the python version I had no mockups to rely on
