### ISSUE TITLE
Plot not automatically displayed

### ISSUE THREAD

**Issue by datawookie** [dominodatalab/low-code-assistant-rstudio#44]
The newly implemented interface for plotting looks good.

However, the generated code assigns the plot to a variable.

```r
df <- read.csv(system.file("sample_data", "penguins.csv", package = "assistDomino"))

library(ggplot2)
plot <- ggplot(df) +
 aes(x = bill_length_mm, y = body_mass_g, colour = species) +
 geom_point(shape = "circle", 
 size = 1.5) +
 scale_color_hue(direction = 1) +
 theme_minimal()
```

It does not, however, evaluate that variable, with the consequence that the plot is not immediately displayed. For a seasoned R user this would not present too much of an obstacle (although it is still perhaps an unexpected behaviour). For a new R user (which I understand to be the target audience for LCA) this is very surprising and they would probably be left wondering where their plot is.

**Comment by daattali** [comment]
I'll let @jp-domino weigh in on this one.

The biggest drawback of the R LCA is that it's not integrated into a notebook, so whatever code the users generate within the LCA wizards just gets inserted into a script document, but the visual output doesn't have a place where it belongs. The same is true for the other R-LCA wizards; clicking the "Insert Code" button does exactly that, it inserts code. It doesn't try to visually show that code somewhere. I'll let JP decide if the plots should be forced to be drawn in graphics device.

**Comment by daattali** [comment]
Done with https://github.com/dominodatalab/low-code-assistant-rstudio/commit/d28f5ee327a22aa0cbaeb22dec62c73bf5e02cbc
