### ISSUE TITLE
Buttons should not be greyed out

### ISSUE THREAD

**Issue by datawookie** [dominodatalab/low-code-assistant-rstudio#46]
In a number of dialogs the **OK** button is greyed out or appears to be disabled. This is misleading since these buttons need to be pressed to proceed.

Actually this doesn't only apply to the **OK** buttons. See third screenshot below.

![image](https://user-images.githubusercontent.com/6134409/208459400-dbb72cd5-ef32-4fb5-9b4a-4452f8e7bcb6.png)
![image](https://user-images.githubusercontent.com/6134409/208459552-76fc1fc7-a065-4556-8bcc-02996eb6296f.png)
![image](https://user-images.githubusercontent.com/6134409/208459602-02ec7505-466a-428a-8bf5-0e7cc267eba2.png)
![image](https://user-images.githubusercontent.com/6134409/208459721-bf403c08-1ca7-4e2b-aec3-5e39abdf87a0.png)

**Comment by daattali** [comment]
The buttons are not greyed out, they simply have white text with a light blue background. That's just the default background colour in the javascript library sweetalert that's used to generate these modals. Any button that is greyed out will be unclickable and the cursor will become a "not allowed" instead of the "hand"

**Comment by datawookie** [comment]
I suggest that you change the "light blue background" to be consistent with the blue background in the other buttons. In the screenshot above you can see the "+ Add" and "Insert Code" buttons. When somebody is working in RStudio this is how they expect "clickable" buttons to appear. If you are happy with the current colouring :+1:. However, when I saw this dialog I was not sure what I was supposed to do to dismiss it. I immediately assumed that the (light blue background) "OK" button was disabled.

**Comment by daattali** [comment]
made them the same blue
